# Generated by Django 4.2.30 on 2026-07-19 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='筋トレカレンダー', max_length=100, verbose_name='名前')),
                ('slug', models.SlugField(default=tracker.models.generate_slug, unique=True, verbose_name='共有URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '共有カレンダー',
                'verbose_name_plural': '共有カレンダー',
            },
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='tracker.calendarroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '筋トレ記録',
                'verbose_name_plural': '筋トレ記録',
                'ordering': ['-date'],
                'unique_together': {('room', 'user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_target', models.PositiveIntegerField(default=3, help_text='1週間に何回筋トレするか', verbose_name='週の目標回数')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tracker.calendarroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '目標',
                'verbose_name_plural': '目標',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
